name: Terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      working-directory: ./terraform
      
    - name: Terraform Plan
      if: github.event.inputs.action == 'apply'
      run: terraform plan -out=plan.tfplan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      working-directory: ./terraform

    - name: Terraform Apply
      if: github.event.inputs.action == 'apply'
      run: terraform apply -auto-approve plan.tfplan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      working-directory: ./terraform

    - name: Remove Terraform Plan File
      if: github.event.inputs.action == 'apply'
      run: rm plan.tfplan
      working-directory: ./terraform

    - name: Terraform Plan Destroy
      if: github.event.inputs.action == 'destroy'
      run: terraform plan -destroy -out=destroy.tfplan
      working-directory: ./terraform

    - name: Terraform Destroy
      if: github.event.inputs.action == 'destroy'
      run: terraform apply -auto-approve destroy.tfplan
      working-directory: ./terraform

    - name: Remove Terraform Destroy Plan File
      if: github.event.inputs.action == 'destroy'
      run: rm destroy.tfplan
      working-directory: ./terraform
